name: Update Google Translate IPs

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  workflow_dispatch:        # 支持手动触发

jobs:
  update-gist:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.8'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
        
    - name: 运行更新脚本
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: python update_gist.py

permissions:
  contents: read
  gists: write